version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
      - image: trufflesuite/ganache-cli
        command: ganache-cli --deterministic
    steps:
      - checkout
      - run:
        - name: Install React Project
        - command: yarn
      - run:
        - name: Lets Test
        - command: yarn test

